version: '2.3'
services:
  keras_jupyter_sample:
    runtime: nvidia
    image: chenaoki/keras_jupyter:0.2 
    container_name: keras_jupyter_sample
    ports:
      - "20002:8888"
    volumes:
      - ./:/notebooks
